### ISSUE TITLE
Upgrade to PyCryptodome?

### ISSUE THREAD

**Issue by rfadams** [RNCryptor/RNCryptor-python#7]
I recently started using the RNCryptor libraries in a few different languages. Thanks for all the great work and documentation.

I was wondering if there was any plans to upgrade the python library to use [PyCryptodome](https://github.com/Legrandin/pycryptodome) and replace PyCrypto? It seems that PyCrypto is unmaintained ([issue](https://github.com/dlitz/pycrypto/issues/285) & [blog](https://theartofmachinery.com/2017/02/02/dont_use_pycrypto.html) discussing) and PyCryptodome is a (mostly) drop-in replacement for of the project. 

If not, would the project be open to a PR from me to upgrade the library? 

Thanks again.

**Comment by ykalchevskiy** [comment]
Hi Robert,

I have no such plans, but I will be glad to review and merge your PR.

**Comment by evandrix** [comment]
*bump*

**Comment by ykalchevskiy** [comment]
Hi @rfadams, are you going to do the upgrade?

**Comment by vistatest** [comment]
Got a deprecation warning:
venv/lib/python3.7/site-packages/Crypto/Random/_UserFriendlyRNG.py:77: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
    t = time.clock()

Whether by switching to PyCryptodome or even to cryptography, please, remove pycrypto dependency before Python 3.8 release.

PyCryptodome is a maintained fork of pycrypto and exposes almost the same API as the old PyCrypto so that most applications could run unmodified. Compatibility with pycrypto is described here:
https://pycryptodome.readthedocs.io/en/latest/src/vs_pycrypto.html

**Comment by furritos** [comment]
Please review PR #9 and advise... thanks!

**Comment by vistatest** [comment]
Thanks.
It's much needed but too late for me - I've already switched to
cryptography package (https://github.com/pyca/cryptography).

**Comment by aliciawyy** [comment]
Hi,
Could you review and merge the previous PR and make a new release please ?

**Comment by ykalchevskiy** [comment]
```
$ pip install rncryptor==3.3.0
Collecting rncryptor==3.3.0
...
Installing collected packages: pycryptodome, rncryptor
Successfully installed pycryptodome-3.8.2 rncryptor-3.3.0
```

Thank you, @furritos!
